FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Zabo Project

Zabo는 교내 구성원들이 온라인에서 손쉽게 자보를 홍보하고, 또 모아볼 수 있도록 도와주는 서비스이다. 

# Group User

API에서 user 모델과 관련된 resource에 대한 설명.

## User [/api/users/{user_id}]

user object에 대한 기본적인 CRUD를 제공한다.

+ Pamameters
    + user_id - Id of a user.

### View a User Detail [GET]

URL에 포함된 id에 해당하는 user의 detail을 가져온다.

+ Response 200 (application/json)

    성공적으로 user_id에 해당하는 유저 정보를 받아올 경우

    + Body
    
            {
                success: true
            }

### Edit a User [PUT]

기존 user를 수정한다.

+ Response 200 (application/json)

    성공적으로 user_id에 해당하는 유저 정보를 수정할 경우
    
    + Body
    
            {
                success: true
            }

### Delete a User [DELETE]

해당 user를 삭제한다.

+ Response 200 (application/json)

    성공적으로 user)id에 해당하는 유저 정보를 삭제할 경우
    
    + Body
    
            {
                success: true
            }

## Users Collection [/api/users/]

user collection에 대한 기본적인 CRUD를 제공한다.

### Create a New User [GET]

URL에 포함된 id에 해당하는 user의 detail을 가져온다.

+ Request

            {
                id: [SPARCS SSO ID]
            }

+ Response 200 (application/json)

    성공적으로 user_id에 해당하는 유저 정보를 받아올 경우

    + Body
    
            {
                success: true
            }
            
+ Response 400 (application/json)
    
    이미 해당 id로 생성된 user가 있을 경우 (duplicated id)
    
    + Body

# Group Zabo

API에서 zabo 모델과 관련된 resource에 대한 설명.

## Zabo [/api/zabos/{zabo_id}]

zabo object에 대한 기본적인 CRUD를 제공한다.

+ Parameters
    + zabo_id - Id of a zabo.

### View a Zabo Detail [GET]

URL에 포함된 id에 해당하는 zabo의 detail을 가져온다.

+ Response 200 (application/json)

    성공적으로 zabo_id에 해당하는 zabo의 정보를 가져온 경우
    
    + Body

            {
                id(String): 고유 id (key for zabo)
                img(String): 게시할 자보 이미지 이름
                event(String): 행사 이름
                writer(String): 게시자 이름 (key for user)
                category(String?): 카테고리
                applyStart(Date): 지원 시작일
                applyEnd(Date): 지원 마감일
                eventStart(Date): 행사 시작일
                eventEnd(Date): 행사 마감일 (게시 마감일)
                description(String): 간략한 설명
                report([String]): 신고한 user 리스트
                toAra(Boolean): 아라에 자동으로 노출시켜줄지의 여부
                isMain(Boolean): 메인 페이지에 띄워지는 자보인지의 여부
            }

### Edit a Zabo [PUT]

기존 zabo를 수정한다.

+ Response 200 (application/json)

    성공적으로 zabo_id에 해당하는 zabo를 수정한 경우
    
    + Body

            {
                success: true
            }

### Delete a Zabo [DELETE]

해당 zabo를 삭제한다.

+ Response 204 (application/json)

    성공적으로 zabo_id에 해당하는 zabo를 삭제한 경우
    
    + Body

## Zabos Collection [/api/zabos]

zabos collection에 대한 기본적인 CRUD를 제공한다.

### List All Zabos [GET]

query가 empty string이면 모든 zabo의 list를 가져온다. query가 있으면 query에 해당하는 zabo list를 가져온다.

+ Request (application/json)

            {
                "query": "SPARCS"
            }

+ Response 200 (application/json)

            {
                
            }

### Create a New Zabo [POST]

새로운 zabo를 생성한다.

+ Response 200 (application/json)

            {
                
            }

### Delete All Zabos [DELETE]

모든 zabo를 삭제한다. **(Admin ONLY)**

+ Response 200 (application/json)

            {
                
            }

## Register/Unregister Main Zabos [/api/zabos/mains/{zabo_id}]

### Register a New Main Zabo [POST]

메인 페이지의 상단에 띄워질 자보로 등록한다.

+ Response 200 (application/json)

    성공적으로 zabo_id에 해당하는 zabo를 main zabo로 등록할 경우
    
    + Body

            {
                success: true
            }

### Unregister a Main Zabo [DELETE]

메인 페이지의 상단에 띄워진 자보를 등록 해제한다.

+ Response 200 (application/json)

    성공적으로 zabo_id에 해당하는 zabo를 main zabo로 등록 해제할 경우
    
    + Body

            {
                success: true
            }

## Main Zabos [/api/zabos/mains]

### List All Main Zabos [GET]

메인 페이지의 상단에 띄워질 3개의 zabo list를 가져온다.

+ Response 200 (application/json)

            [
                {
                    id: ...,
                    ...,
                    isMain: true
                },
                {
                    id: ...,
                    ...,
                    isMain: true
                },
                {
                    id: ...,
                    ...,
                    isMain: true
                }
            ]

### Reset All Main Zabos [DELETE]

메인 페이지의 상단에 띄워질 3개의 zabo를 초기화한다. **(Admin Only)**

+ Response 200 (application/json)

            {
                success: true
            }
            
## Zabos with Condition [/api/zabos/{condition}]

특정 condition을 만족하는 자보를 가져올 때 필요한 API이다. 카테고리별 자보, 인기 자보, 듀 임박 자보, 특정 단체의 자보를 받아올 수 있다.

+ Parameter
    + condition - 받아오고자 하는 zabo list의 condition (카테고리, 인기, 듀 임박, 특정 단체)

### List All Zabos in the Given Condition [GET]

query가 empty string이면 parameter로 주어진 condition에 해당하는 zabo list를 가져온다.
query가 있으면 주어진 condition 내에서 query에 해당하는 zabo list를 가져온다.

+ Request (application/json)

            {
                "query": "SPARCS"
            }

+ Response 200 (application/json)

            {
                
            }
            
## Report Zabo [/api/zabos/:zabo_id/report]

자보를 신고할 때 필요한 API이다.

### Report a Zabo [POST]

zabo_id에 해당하는 자보를 신고한다.

+ Response 200 (application/json)

            {
                
            }

# Group Favorite

즐겨찾기와 관련된 API 설명.

## User's Favorite Zabo [/api/users/:user_id/likes/zabos]

유저가 관심있는 자보를 받아오는 API이다.

### List All Favorite Zabos of a User [GET]

유저가 즐겨찾기한 자보 / 즐겨찾기한 단체의 자보를 모두 받아온다.

+ Response 200 (application/json)

            {
                
            }

## Favorites to Zabo [/api/users/:user_id/likes/zabos/:zabo_id]

특정 자보 즐겨찾기와 관련된 API이다.

### Register a Zabo as a Favorite Zabo [POST]

zabo_id에 해당하는 자보를 user_id를 가진 유저 즐겨찾는 자보로 등록한다.

+ Response 200 (application/json)

            {
                
            }

### Unregister a Zabo as a Favorite Zabo [DELETE]

zabo_id에 해당하는 자보를 user_id를 가진 유저 즐겨찾는 자보에서 등록 해제한다.

+ Response 200 (application/json)

            {
                
            }

## Favorites to Group [/api/users/:user_id/likes/:group]

특정 단체 즐겨찾기와 관련된 API이다.

### Register a Group as a Favorite Group [POST]

group에 해당하는 단체를 user_id를 가진 유저의 즐겨찾는 단체로 등록한다.

+ Response 200 (application/json)

            {
                
            }

### Unregister a Group as a Favorite Group [DELETE]

group에 해당하는 단체를 user_id를 가진 유저의 즐겨찾는 단체에서 등록 해제한다.

+ Response 200 (application/json)

            {
                
            }